### ISSUE TITLE
Where do I find .h5 files?

### ISSUE THREAD

**Issue by ibadami** [Cadene/tensorflow-model-zoo.torch#1]
Hi
I am trying to run inceptionresnetv2 using pytorch. 
I do not have .h5 files. Where can I get it from?

Am I missing something?

**Comment by Cadene** [comment]
Sorry for the late answer.

You don't need any .h5 files, but to load the [.pth file containing the pretrained weights](https://github.com/Cadene/tensorflow-model-zoo.torch/blob/master/inceptionresnetv2/pytorch_load.py#L8).

The .pth file will be automatically downloaded if you have the `pretrained` parameter set to `True` (it is set that way by default).

```python
import torch
from inceptionresnetv2.pytorch_load import inceptionresnetv2
net = inceptionresnetv2(pretrained=True)
input = torch.autograd.Variable(torch.ones(1,3,299,299))
output = net.forward(input)
```

Beware, it is meant to be used with a mean of 0.5 and a std of 0.5:

[See in the imagenet training/testing code](https://github.com/pytorch/examples/blob/master/imagenet/main.py#L100)

```python
normalize = transforms.Normalize(mean=[0.5, 0.5, 0.5],
                                     std=[0.5, 0.5, 0.5])
```

**Comment by ibadami** [comment]
I see. Thank you so much.
