### ISSUE TITLE
Bad performance in PyTorch

### ISSUE THREAD

**Issue by cg563** [Cadene/tensorflow-model-zoo.torch#3]
I am trying to use the pretrained Inception v4 model in PyTorch. The model's classification accuracy on ImageNet validation set is extremely poor (1% top-1, 28% top-5). I am normalizing the input as described in http://pytorch.org/docs/master/torchvision/models.html. Is there any other preprocessing that I'm not doing? Thanks.

**Comment by Cadene** [comment]
Please try my other lib: https://github.com/Cadene/pretrained-models.pytorch#toy-example

Just replace `model_name = 'fbresnet152'` by `model_name = 'inceptionv4'` in the toy-example code.
The model is the same than in this lib, but I am trying to build a common interface between each pretrained convnets (be it on imagenet or other dataset).

It should work. Let me know.

**Comment by Cadene** [comment]
I also provide the imagenet code if you want to evaluate a pretrained model:
https://github.com/Cadene/pretrained-models.pytorch/blob/master/test/imagenet.py

**Comment by cg563** [comment]
Thanks for the quick reply! I tried the other repo but it gives me an error:

RuntimeError: inconsistent tensor size at pytorch/pytorch/torch/lib/TH/generic/THTensorCopy.c:85

from line 303 of inceptionv4.py.

**Comment by Cadene** [comment]
Did you try this ?
```
cd pretrained-models.pytorch
python test/imagenet.py /local/data/imagenet_2012/images --arch inceptionv4 -e --pretrained
```

It seems to work for me

**Comment by cg563** [comment]
I figured out what the problem with the original repo was - I assumed the 1001th class is the background when it's the 1st class.

**Comment by Cadene** [comment]
Yes you are right.
I will solve some issues in few days. Sorry.
