### ISSUE TITLE
Could you please port NASNet-A_Mobile_224 model?

### ISSUE THREAD

**Issue by wandering007** [Cadene/tensorflow-model-zoo.torch#6]
Thanks for the great work on porting [nasnet](https://github.com/tensorflow/models/tree/master/research/slim/nets/nasnet). Nasnet is too complicated. Could you please also port NASNet-A_Mobile_224 model? Many Thanks.

**Comment by Cadene** [comment]
@wandering007 Sorry for the late answer. I don't plan to do it at the moment. If you really need it, you should have a look at our porting code: https://github.com/Cadene/tensorflow-model-zoo.torch/tree/master/nasnet

Don't hesitate to contact me if you encounter any problem.

**Comment by tonylins** [comment]
@wandering007 Hi, have you done the porting of NASNet-A_Mobile_224? Thanks!

**Comment by wandering007** [comment]
@tonylins Yes, I just released it for you :-) https://github.com/wandering007/nasnet-pytorch
