### ISSUE TITLE
url of inceptionv4 model cannot be open

### ISSUE THREAD

**Issue by wzmsltw** [Cadene/tensorflow-model-zoo.torch#9]
Hi

I found that the url of inceptionv4 model : "http://webia.lip6.fr/~cadene/Downloads/inceptionv4-97ef9c30.pth" cannot be linked. Can you give a new download link of this model? Thank you so much!

**Comment by Cadene** [comment]
This one works: https://github.com/Cadene/pretrained-models.pytorch/blob/master/pretrainedmodels/models/inceptionv4.py#L12

**Comment by kaifeng777** [comment]
Hello, I used a new pre-trained model and this problem occurred
keyError: 'unexpected key "last_linear.bias" in state_dict'
